---

- name: Ensure EPEL is enabled
  yum:
      name: epel-release
      state: present
  become: True
- name: Ensure libselinux-python is present
  yum:
      name: libselinux-python 
      state: present
  become: True
- name: Ensure libsemanage-python is present
  yum:
      name: libsemanage-python
      state: present
  become: True
- name: Ensure NTP is installed
  yum:
      name: ntp
      state: present
  become: True
- name: Ensure the timezone is set to UTC
  file:
      src: /usr/share/zoneinfo/GMT
      dest: /etc/localtime
      state: link
  become: True
- name: Ensure the NTP service is running and enabled
  service:
      name: ntpd
      state: started
      enabled: True
  become: True
- name: Ensure FirewallD is installed
  yum:
      name: firewalld
      state: present
  become: True
- name: Ensure FirewallD is running
  service:
      name: firewalld
      state: started
      enabled: True
  become: True
- name: Ensure SSH can pass the firewall
  firewalld:
      service: ssh
      state: enabled
      permanent: True
      immediate: True
  become: True
